### ISSUE TITLE
Is this app related to Repoting API?

### ISSUE THREAD

**Issue by satoshinishimura-fc** [iTwin/imodel-reporter#22]
I think this app is related to [Reporting API](https://developer.bentley.com/apis/insights/) because of its name. But, it is a little difficult for me to find the code that calls the API in the src directory. I appreciate it if someone answers the question. If this app does not use reporting API then please let me know the difference between the app and API. Thank you in advance.

**Comment by candcconsulting** [comment]
No this is not using the reporting api.  This pulls the iMOdel locally and then runs queries locally against the iModel.  The app will incur egress credits on an iTwin subscription.
However, if you have a local snapshot iModel, then the same functions will work if you open the local snapshot iModel (incurring no credits)
